# 
# Travis CI script for bindings
# Tag any branch with release-* for release
#
git:
  depth: 2
  # Check that cmake is working properly
  submodules: false
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export CXX=/usr/local/bin/g++-6
    export CC=/usr/local/bin/gcc-6
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CXX=g++-6
    export CC=gcc-6
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    wget -q https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.zip \
      && echo "Downloaded archive"
    unzip -q boost_1_62_0.zip -d boost \
      && echo "Extracted archive"
    BDIR="$(pwd)/boost"
    export BOOST_ROOT="${BDIR}" \
      && echo "Set boost root to ${BDIR}"
  fi
language: node_js
node_js:
- '10'
- '8'
- '6'
os:
- linux
- windows
- osx
dist: xenial
osx_image: xcode10.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:rexut/factory'
    packages:
    - libboost1.62-dev
    - unixodbc
    - unixodbc-dev
    - cmake
    - gcc-6
    - g++-6
  homebrew:
    packages:
    - unixodbc
    - cmake
    - gcc@6
    - boost@1.62
script: |
  npm run compile
  echo 'Skipping tests'
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: HtohRb7iVHWZJL2MoeyBXabbagqyrOWO24kcbX5qkUcjKckV4257xRAuG59TiLU1NadtCEg+vEIR4uHV0FnX7Z5wXTGsXeTebLcUHEv3n4n2GYOKAKbsDclpZiAb1aemQjbWRg7Cxu9OiEJ7i3nqT6SYKaZdeNvm758biMSB9uJHGOjn8RccvtH9cwIzbhkR1fIwRxv+XxPfQPK9z3XHRO9MOtWcGxSF3SuQ2DKVSd84oeJXob5lKQaapv1YradnMwij64QZNEftr2A4O3Ns0czW1TLzVpZEJr/+ulL9xeIY6dGFiQPSDjvunqsfsA1mkaQUnU1vI5JBXlIVk8/17dh/b6xwah2fhYwyBsv6kBEBknUcO9RRhlEEixSzoX874vw9ocQ2I+AxM6GXTe7hBPTfx4x+1pXY7cAl6ru/rn8XoeVH9rPAzTu/OqCWP+3lbSV8WZSbl2KpRHvWNlBm/UH2AtnIzZ6Lfd2Z7s3bRsuryRYhASZI5XY2JZesYGAWLWOBlu9nEVpcWp/DuNa8gJ901KbLNWd2jucdFxRbga5VEdrByK7rL66rePOrXEkqYCr60GrA9Zio1ijn2rnSKEdun1LtVOnmWREgQYmoeOrcK8MkRH0i77uW1xurRGWaIqaAO/TLMg7GChJLLOdNMc9xXzL9WxN9QE73zQ62iLI=
  file: build/Release/*
  on:
    repo: theconst/aodbc
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^release-.*$"
