git:
  depth: 2
  # Travis fails to find directories during the build because of manual checkout
  submodules: false
language: node_js
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export CXX=/usr/local/bin/g++-6
    export CC=/usr/local/bin/gcc-6
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CXX=g++-6
    export CC=gcc-6
  fi
node_js:
- '10'
matrix:
  include:
      - os: linux
        dist: xenial
        addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - unixodbc
            - unixodbc-dev
            - cmake
            - gcc-6
            - g++-6
      - os: osx
        osx_image: xcode10.1
        addons:
          homebrew:
            packages:
            - unixodbc
            - cmake
            - gcc@6
script: echo 'Skipping tests'
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HtohRb7iVHWZJL2MoeyBXabbagqyrOWO24kcbX5qkUcjKckV4257xRAuG59TiLU1NadtCEg+vEIR4uHV0FnX7Z5wXTGsXeTebLcUHEv3n4n2GYOKAKbsDclpZiAb1aemQjbWRg7Cxu9OiEJ7i3nqT6SYKaZdeNvm758biMSB9uJHGOjn8RccvtH9cwIzbhkR1fIwRxv+XxPfQPK9z3XHRO9MOtWcGxSF3SuQ2DKVSd84oeJXob5lKQaapv1YradnMwij64QZNEftr2A4O3Ns0czW1TLzVpZEJr/+ulL9xeIY6dGFiQPSDjvunqsfsA1mkaQUnU1vI5JBXlIVk8/17dh/b6xwah2fhYwyBsv6kBEBknUcO9RRhlEEixSzoX874vw9ocQ2I+AxM6GXTe7hBPTfx4x+1pXY7cAl6ru/rn8XoeVH9rPAzTu/OqCWP+3lbSV8WZSbl2KpRHvWNlBm/UH2AtnIzZ6Lfd2Z7s3bRsuryRYhASZI5XY2JZesYGAWLWOBlu9nEVpcWp/DuNa8gJ901KbLNWd2jucdFxRbga5VEdrByK7rL66rePOrXEkqYCr60GrA9Zio1ijn2rnSKEdun1LtVOnmWREgQYmoeOrcK8MkRH0i77uW1xurRGWaIqaAO/TLMg7GChJLLOdNMc9xXzL9WxN9QE73zQ62iLI=
  file: build/Release/cacheodbc.node
  on:
    repo: theconst/aodbc
    branches:
      only:
        - release
